#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//May everyone rest
//LOL, found Alvin's code on the internet.

void initializeRobot() {
int joystickvalues [2][2]; 
	int fine_adjustment;
	int buttonthing;
	int carmode;
	carmode = 0;
	}

task main() {
	
	while (true){
		// Update the values of the variables storing the joystick positions.
		getJoystickSettings(joystick);
	 	joystickvalues [1][1] = joystick.joy1_x1;
		joystickvalues [1][2] = joystick.joy1_y1;
		joystickvalues[2][1] = joystick.joy1_x2;
	 	joystickvalues[2][2] = joystick.joy1_y2;
		buttonthing = joystick.joy1_TopHat;

	 //filter
	 
	 if (abs(joystickvalues) < 28) {
		joystickvalues = 0;
		}
	//scaling it down
	 
	 if (joystickvalues > 28) {
		joystickvalues = joystickvalues -28;
		}
	 
	 if (joystickvalues < -28) {
		joystickvalues = joystickvalues +28;
		}
	if (joystickvalues[1][2] > 0 && abs(joystickvalues[2][2]) > 0 && abs(joystickvalues[2][1]) >0) {
	fine_adjustment = 1 / (1 +joystickvalues[1][2]);
	}
	else {
	fine_adjustment = 0;
	}

	if (carmode = 0) {
	//code derived from the fact that q1+,q2-,q3-,q4+ cancels out horizontal movement and only allows vertical, by changing the signs of each value,
	//a single direction is yielded in a different direction, if the motors rotate at different values, non perpendicular directions are achieved
	  motor[Q1] = ( joystickvalues[2][2] - joystickvalues[2][1] ) - fine_adjustment; 
	 motor[Q2] = ( -joystickvalues[2][2] - joystickvalues[2][1]  ) - fine_adjustment;
	 motor[Q3] = ( -joystickvalues[2][2] + joystickvalues[2][1]  )-fine_adjustment ;
	 motor[Q4] = (  joystickvalues[2][2] + joystickvalues[2][1]  ) - fine_adjustment;
	 }

	 //rotate
	 if (joystickvalues[2][1]>92 && joystickvalues[2][1]==0 && joystickvalues[2][2]==0 && carmode = 0) {
	 motor[Q1] = (  100 )- fine_adjustment ;
	 motor[Q2] = ( 100 ) - fine_adjustment;
	 motor[Q3] = ( 100 ) -fine_adjustment ;
	 motor[Q4] = (  100)-fine_adjustment ;
	 wait(0.5);
   }

	 if (joystickvalues[2][1]<-92 && joystickvalues[2][1]==0 && joystickvalues[2][2]==0 && carmode = 0) {
	 motor[Q1] = (  -100 )- fine_adjustment ;
	 motor[Q2] = ( -100 ) - fine_adjustment;
	 motor[Q3] = ( -100 ) - fine_adjustment;
	 motor[Q4] = (  -100  ) - fine_adjustment;
	 wait(0.5);
   }
   
   if (buttonthing == 0 && carmode ==0){
	 carmode =1;
	 }
	if (buttonthing == 0 && carmode ==1){
	carmode = 0;
	}
	
	if (carmode = 1){
	motor[Q4] = joystickvalues[1][2];
	motor[Q3] = jostickvalues[1][2];
	motor[Q2] = joystickvalues[1][1];
	motor[Q1] = joystickvalues[1][1];

   
   
   
	}
	}
