#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//totally not a ripoff
//Brian Kwong, Allan Wang, Jonathan Quang, some parts of Alvin Lin's

task main() {
	int joystickvalues [2][2]; 
	int fine_adjustment;
	while (true){
		// Update the values of the variables storing the joystick positions.
		getJoystickSettings(joystick);
	 	joystickvalues [1][1] = joystick.joy1_x1;
		joystickvalues [1][2] = joystick.joy1_y1;
		joystickvalues[2][1] = joystick.joy1_x2;
	 	joystickvalues[2][2] = joystick.joy1_y2;

	 //filter
	 
	 if (abs(joystickvalues) < 28) {
		joystickvalues = 0;
		}
	

	 //scaling it down
	 
	 if (joystickvalues > 28) {
		joystickvalues = joystickvalues -28;
		}
	 
	 if (joystickvalues < -28) {
		joystickvalues = joystickvalues +28;
		}
	if (joystickvalues[1][2] > 0 && abs(joystickvalues[2][2]) > 0 && abs(joystickvalues[2][1]) >0) {
	fine_adjustment = 1 / (1 +joystickvalues[1][2]);
	}
	else {
	fine_adjustment = 0;
	}
//direct movement, Alvin's code is too good, im pretty sure alvin copied it too
	  motor[Q1] = ( joystickvalues[2][2] - joystickvalues[2][1] ) - fine_adjustment;
	 motor[Q2] = ( -joystickvalues[2][2] - joystickvalues[2][1]  ) - fine_adjustment;
	 motor[Q3] = ( -joystickvalues[2][2] + joystickvalues[2][1]  )-fine_adjustment ;
	 motor[Q4] = (  joystickvalues[2][2] + joystickvalues[2][1]  ) - fine_adjustment;

	 //rotate
	 if (joystickvalues[2][1]>92 && joystickvalues[2][1]==0 && joystickvalues[2][2]==0) {
	 motor[Q1] = (  100 )- fine_adjustment ;
	 motor[Q2] = ( 100 ) - fine_adjustment;
	 motor[Q3] = ( 100 ) -fine_adjustment ;
	 motor[Q4] = (  100)-fine_adjustment ;
   }

	 if (joystickvalues[2][1]<-92 && joystickvalues[2][1]==0 && joystickvalues[2][2]==0) {
	 motor[Q1] = (  -100 )- fine_adjustment ;
	 motor[Q2] = ( -100 ) - fine_adjustment;
	 motor[Q3] = ( -100 ) - fine_adjustment;
	 motor[Q4] = (  -100  ) - fine_adjustment;
   }
	}
	}
