#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main {
	while (true) {
		getJoystickSettings(joystick);
		int y1 = joystick.joy1_y1;
		int y2 = joystick.joy1_y2;
		int x1 = joystick.joy1_x1;
		int x2 = joystick.joy2_x2;
		int pos = 50;
		
		if(y1 > pos){
			motor[Q1] = 1
			motor[Q2] = 1
		}
		else if(x1 > pos & y1 > pos){
			motor[Q1] += pos
			motor[Q2] += pos
		}
		else if(y1 == 0){
			motor[Q1] == 0
			motor[Q2] == 0
		}	
		if (y1 > pos){
			motor[Q3] = 1
			motor[Q4] = 1
		}
		else if(x1 > pos & y1 > pos){
			motor[Q3] += pos
			motor[Q4] += pos
		}
		else if(y1 == 0){
			motor[Q3] == 0
			motor[Q4] == 0
		}
		
	}
}

