#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     gyro,                sensorI2CCustom9V)
#pragma config(Motor,  mtr_S2_C1_1,     left_M1,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     left_M2,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     right_M1,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     right_M2,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     arm_rotationMotor, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S2_C4_1,    plow_1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C4_2,    plow_2,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>
void initializeRobot();

task main() {

  initializeRobot();
  waitForStart();

}

void initializeRobot() {
}
