#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     liftLbottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     liftRbottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     LED,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     leadL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     leadR,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoL,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoR,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    lockL,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    lockR,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    auton,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main(){
	//waitForStart();
  while(true){
    getJoystickSettings(joystick);
  	int y2 = joystick.joy1_y2;
 		int x2 = joystick.joy1_x2;

 		if ((abs(y2)) < 15){
 			y2 = 0;
 		}
 		if ((abs(x2)) < 15){
 			x2 = 0;
 		}
		if (joy1Btn(10)) {
			break;
		}

 		motor[left] = (y2/2) - (x2/2);
 		motor[right] = (y2/2) + (x2/2);

	}
}
