#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontRight,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     donutLift,             tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     supportMotor,  tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void initializeRobot() {

}
task main{
  initializeRobot();
  waitForStart();
  while (true)
  {
    getJoystickSettings(joystick);

    //motors
    if (abs(joystick.joy1_y1) > 10) {
      motor[frontLeft]= -joystick.joy1_y1;
      motor[backLeft] = -joystick.joy1_y1;
      }else {
      motor[frontLeft]= 0;
      motor[backLeft] = 0;
    }
    if (abs(joystick.joy1_y2) > 10) {
      motor[backRight] = joystick.joy1_y2;
      motor[frontRight] = joystick.joy1_y2;
      } else {
      motor[backRight] = 0;
      motor[frontRight] = 0;
    }

    //ramp & support servo pins
    if (joy1Btn(5) == 1)
    {servo[servo1] = 300;
      }else{
      servo[servo1] = 0;
    }
    //support motor
    if (joy1Btn(7) == 1)
    {motor[supportMotor] = 100;
      }else{
      motor[supportMotor] = 0;
    }
    if (joy1Btn(4) == 1)
    {
      motor[supportMotor] = -100;
    }
    //donutlift up and stationary
    if (joy1Btn(6) == 1)
    {motor[donutLift] = 100;
      }else{
      motor[donutLift] = 0;
    }
    //donutlift down
    if (joy1Btn(8) == 1)
    {
      motor[donutLift] = -100;
    }
  }
  }
