#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    fd_left,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    fd_right,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    back_left,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    back_right,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  VectorDriveCode.c
 *
 *
 *  Created by Abhimanyu Ghosh on 2/14/11.
 *  Copyright 2011 Abhimanyu Ghosh, Stuyvesant High School FTC Robotics. All rights reserved.
 *
 */

// Some busy-work...

#include <JoystickDriver.c>

#define servo1Deadband 127
#define servo2Deadband 127
#define servo3Deadband 127
#define servo4Deadband 127

#define servo1negative90 0
#define servo2negative90 0
#define servo3negative90 0
#define servo4negative90 0

#define servo1positive90 255
#define servo2positive90 255
#define servo3positive90 255
#define servo4positive90 255

void setAngle(int servoIndex, int angle);


task main() {

	while(true) {

	getJoystickSettings(joystick);
	int angle = joystick.joy1_x1;
	if (angle < -90) {angle = -90;}
	if (angle > 90) {angle = 90;}
//  setAngle(1, angle_set);
  //setAngle(2, angle_set);
 // setAngle(3, angle_set);
 // setAngle(4, angle_set);
int servSet = 0;
	servSet = (int)(((servo1positive90 - servo1negative90) / 90) * angle);
    servo[fd_left] = 255;
	}
}

void setAngle(int servoIndex, int angle) {

  int servoSet = angle;

  if (servoIndex == 1) {
    servoSet = (int)(((servo1positive90 - servo1negative90) / 90) * angle);
    servo[fd_left] = servoSet;
  }

  if (servoIndex == 2) {
    servoSet = (int)(((servo2positive90 - servo2negative90) / 90) * angle);
    servo[fd_right] = servoSet;
  }

  if (servoIndex == 3) {
   servoSet = (int)(((servo3positive90 - servo3negative90) / 90) * angle);
    servo[back_left] = servoSet;
  }

  if (servoIndex == 4) {
    servoSet = (int)(((servo4positive90 - servo4negative90) / 90) * angle);
    servo[back_right] = servoSet;
  }

}
