#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     r1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     r2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     r3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     r4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main () {

	while true ()
		getJoystickSettings(joystick);
		int y1 = joystick.joy1_y1;
		int y2 = joystick.joy1_y2;
		int x1 = joystick.joy1_x1;
		int x2 = joystick.joy1_x2;

		if (y1 > 50) {
			//right side forward
			motor [r1] = y1;
			motor [r2] = y2;
		}

		else {
			motor [r1] = 0;
			motor [r2] = 0;
		}

		if (y1 < -50) {
			//left side forward
			motor [r1] = y1;
			motor [r2] = y2;
		}

		else {
			motor [r1] = 0;
			motor [r2] = 0;
		}

		if (x1 > 50) {
			//forward
			motor [r3] = x1;
			motor [r4] = x2;
		}

		else {
			motor [r3] = 0;
			motor [r4] = 0;
		}

		if (
	}

}
