#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main() {
	while (true) {
		getJoystickSettings(joystick);
		int y1 = joystick.joy1_y1;
		int x1 = joystick.joy1_x1;

		if ((x1 < 25 && x1 > -25) &&
			(y1 < 25 && y1 > -25)) {}

		else if (y1 < 25 && y1 > -25) {
			if (x1 > 25) {
				// go right
			}
			if (x1 < -25) {
				// go left
			}
		}
		else if (x1 < 25 && x1 > -25) {
			if (y1 > 25) {
				// go up
			}
			if (y1 < -25) {
				// go down
			}
		}
		else if ((x1 > 25 || x1 < -25) &&
			(y1 > 25 || y1 < -25)) {
			if (x1 > 25) {
				if (y1 > 25) {
					// go NE
				}
				if (y1 < -25) {
					// go SE
				}
			}
			if (x1 < -25) {
				if (y1 > 25) {
					// go NW
				}
				if (y1 < -25) {
					// go SW
				}
			}
		}
	}
}
