#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int nullRad = 50;

int x1 = 0;
int y1 = 0;
int x2 = 0;

int scale(int scaleThis) {
	return ((scaleThis - nullRad) * (100/(128 - nullRad)));
}

void goNorth() {
	motor[Q1] = scale(y1);
	motor[Q2] = -scale(y1);
	motor[Q3] = scale(y1);
	motor[Q4] = -scale(y1);
}
void goSouth() {
	motor[Q1] = -scale(y1);
	motor[Q2] = scale(y1);
	motor[Q3] = -scale(y1);
	motor[Q4] = scale(y1);
}
void goWest() {
	motor[Q1] = scale(x1);
	motor[Q2] = scale(x1);
	motor[Q3] = -scale(x1);
	motor[Q4] = -scale(x1);
}
void goEast() {
	motor[Q1] = -scale(x1);
	motor[Q2] = -scale(x1);
	motor[Q3] = scale(x1);
	motor[Q4] = scale(x1);
}

void spinClockwise() {
	motor[Q1] = scale(x2);
	motor[Q2] = scale(x2);
	motor[Q3] = scale(x2);
	motor[Q4] = scale(x2);
}
void spinCounterClockwise() {
	motor[Q1] = -scale(x2);
	motor[Q2] = -scale(x2);
	motor[Q3] = -scale(x2);
	motor[Q4] = -scale(x2);
}

task main()
{
	while (true)
	{
		getJoystickSettings(joystick);
		x1 = joystick.joy1_x1;
		y1 = joystick.joy1_y1;
		x2 = joystick.joy1_x2;



		//energy conservation
		while (abs(x1) <= nullRad && abs(y1) <= nullRad
			&& abs(x2) <= nullRad) {wait1Msec(25);}
	}
}
