#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main (){
    int x1,y1,x2,y2;
    while(true){
        getJoystickSettings(joystick);
         x1 = joystick.joy1_x1;
         y1 = joystick.joy1_y1;
         x2 = joystick.joy1_x2;
         y2 = joystick.joy1_y2;
        
        if(abs(y1) > 10){
            motor[Q1]=-y1;
            motor[Q2]=y1;
            motor[Q3]=y1;
            motor[Q4]=-y1;
        }
        else if(abs(x1) > 10){
            motor[Q1]=x1;
            motor[Q2]=x1;
            motor[Q3]=-x1;
            motor[Q4]=-x1;
        }
        else{
            motor[Q1]=0;
            motor[Q2]=0;
            motor[Q3]=0;
            motor[Q4]=0;
        }
    }
    
}
