//
//  zsteven.c
//  
//
//  Created by Steven Zhang on 11/5/14.
//
//

#include "zsteven.h"
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main {

if (y1 > 50) {
    motor [Q1] = 100;
    motor [Q2] = 100;
}
  
    }
    else (y1 == 0) {
        motor [Q1] = 0;
        motor [Q2] = 0;
    }
    if (y1 < -50 ) {
        motor [Q1] = -100;
        motor [Q2] = -100;
    }
else (y1 < -50) {
    motor [Q1] = 0;
    motor [Q2] = 0;
}