#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Q1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Q2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Q3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Q4,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main {
	while(true){
		getJoystickSettings(joystick);
		int x1 = joystick.joy1_x1;
		int y1 = joystick.joy1_y1;
		int x2 = joystick.joy1_x2;
	 	int y2 = joystick.joy1_y2;
 		int radius = 25;
 		if (y1 > radius){
 			motor[Q1] = y1;
 			motor[Q2] = y1;
 			
 			motor[Q1] = 0;
 			motor[Q2] = 0;
 		}
 		if (y2 > radius) {
<<<<<<< HEAD
=======
<<<<<<< HEAD
 			motor[Q3] = 100;
 			motor[Q4] = 100;
 		}
 	}
}
=======
>>>>>>> cbd5d0317d07b5d17c4a8eb3b156f14e2e344cf3
 			motor[Q3] = y2;
 			motor[Q4] = y2;
 			
 			else 
 				motor[Q3] = 0;
 				motor[Q4] = 0;
 		}
 	}
<<<<<<< HEAD
		
=======
		
>>>>>>> 7274cd28aaa0985063a3dc43f605e9af19d7688d
>>>>>>> cbd5d0317d07b5d17c4a8eb3b156f14e2e344cf3
