#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Compressor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Solenoid,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    cannonServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main() {
  //initializeRobot();
  //waitForStart();

	int servoAngle = 200;

  while(true) {
    getJoystickSettings(joystick);

    motor[rightMotor] = joystick.joy1_y1;
    motor[leftMotor] = joystick.joy1_y2;

    //servo floor & ceiling
    if (servoAngle > 255) {
    	servoAngle = 255;
    }else if (servoAngle < 0) {
    	servoAngle = 0;
    }
    //servo up / down

    if (joy1Btn(5) == 1) {
    	servoAngle = servoAngle - 1;
      wait1Msec(5);
    }
    else if (joy1Btn(7) == 1) {
    	servoAngle = servoAngle + 1;
    	wait1Msec(5);
    }
    else {
    	servoAngle = servoAngle;
    }

    //set servo to angle
    servo[cannonServo] = servoAngle;

    //compressor / solenoid activation
    if (joy1Btn(8) == 1) {
    	motor[Compressor] = 255;
    }
    else {
    	motor[Compressor] = 0;
  	}
  	if (joy1Btn(6) == 1) {
  		motor[Solenoid] = 200;
  	}
  	else {
  		motor[Solenoid] = 0;
		}





  }
}
